### ISSUE TITLE
suppress message in kernelshap

### ISSUE THREAD

**Issue by Yelong-Z** [ModelOriented/kernelshap#105]
Thank you for developing so kind package! But, when I apply this function, there was a problem for suppressing message.

The scrits like:
  library(kernelshap)
  ks <- kernelshap(model_final,X=training_data,bg_X = training_data, verbose = FALSE)

output:
1/1 [==============================] - 0s 21ms/step
1/1 [==============================] - 0s 18ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 2ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 2ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 2ms/step
19/19 [==============================] - 0s 2ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 2ms/step
19/19 [==============================] - 0s 2ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 1ms/step
19/19 [==============================] - 0s 1ms/step

I try 2 ways to suppress this messages, but those ways do not work.
`  suppressMessages({
    ks <- kernelshap(model_final,X=training_data,bg_X = training_data, verbose = FALSE)
  })`

`invisible(capture.output(kernelshap(model_final,X=training_data,bg_X = training_data, verbose = FALSE)))`

**Comment by mayer79** [comment]
By setting `verbose = FALSE`, you are actually suppressing the progress bar of `kernelshap()`. 

Most probably, what you see is the progress bar of the predict function of your model. Is it a Keras model? In that case, you would also need to pass `verbose = 0`. But since `verbose` is already taken by `kernelshap()`, I think you will need to pass an explicit pred_fun, just like

```r
pred_nn <- function(model, data) {
  predict(model, data, batch_size = 1e4, verbose = 0)
}
```

And then `kernelshap(...., pred_fun = pred_nn)`.

Let me know if it works or if this does not solve the problem.

**Comment by Yelong-Z** [comment]
Actually, the model is Keras model.
Thank you so much! It works very well by setting pred_fun = pred_nn.

**Comment by mayer79** [comment]
Sweet, thx for checking.
