### ISSUE TITLE
Predictions must be numeric!

### ISSUE THREAD

**Issue by Xiangjun-tech** [ModelOriented/kernelshap#148]
after I ran this code:
lrn_lg=lrn("classif.lightgbm",id="light",
             predict_type="prob",predict_sets=c("train","test"))

pshap_lg<-kernelshap(
  lrn_lg,
  X=X_explain,
  bg_X=bg_X,
  feature_names=mytask_encode$feature_names
)

I got errors:
> pshap_lg<-kernelshap(
+   lrn_lg,
+   X=X_explain,
+   bg_X=bg_X,
+   feature_names=mytask_encode$feature_names
+ )
Error in align_pred(pred_fun(object, bg_X, ...)) : 
  Predictions must be numeric!

all features in x_explain are numeric.
how to solve this error?

**Comment by mayer79** [comment]
The error is about predictions, not feature values.

What is the result of `predict(lrn_lg, head(train))`?

**Comment by Xiangjun-tech** [comment]
Thanks. I have resolved this issue, which was caused by an update to the kernelshap package (now updated to version 0.7.1). According to the latest official documentation, when using an mlr3 model with the kernelshap function, an additional parameter predict_type = "prob" needs to be added.

**Comment by mayer79** [comment]
Ahhh, right! Thx for digging into this.
